from setuptools import setup, find_packages

setup(
    name="aetherflow-backend",
    version="0.1.0",
    description="AetherFlow Backend - Decentralized Federated AI for Urban Mobility on Hedera",
    author="AetherFlow Team",
    author_email="team@aetherflow.io",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn[standard]>=0.24.0",
        "pydantic>=2.5.0",
        "sqlalchemy>=2.0.23",
        "alembic>=1.12.1",
        "python-dotenv>=1.0.0",
        "httpx>=0.25.2",
        "cryptography>=41.0.7",
        "hashlib-compat>=1.0.1",
        "hedera-sdk-py>=2.30.0",
        "numpy>=1.24.3",
        "pandas>=2.1.3",
        "scikit-learn>=1.3.2",
        "tensorflow>=2.15.0",
        "torch>=2.1.1",
        "web3>=6.11.3",
        "aiofiles>=23.2.1",
        "python-multipart>=0.0.6",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.3",
            "pytest-asyncio>=0.21.1",
            "pytest-cov>=4.1.0",
            "black>=23.11.0",
            "flake8>=6.1.0",
            "mypy>=1.7.1",
            "pre-commit>=3.5.0",
        ],
        "test": [
            "pytest>=7.4.3",
            "pytest-asyncio>=0.21.1",
            "pytest-cov>=4.1.0",
            "httpx>=0.25.2",
        ]
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)